@echo off
echo ========================================
echo  Nks EduOrbit — STUDENT APK Build
echo ========================================

:: ── Version — update BOTH values for every release ──────────────────────────
set VERSION=7.4.48
set VERSION_CODE=145
:: ─────────────────────────────────────────────────────────────────────────────

:: [PRE] Stale .bak cleanup
if exist capacitor.config.ts.bak (
  echo [PRE] WARNING: stale .bak सापडला — cleanup...
  del capacitor.config.ts.bak >nul 2>&1
)

:: [PRE] Restore student config
echo [PRE] Student config restore (capacitor-student.config.ts → capacitor.config.ts)...
copy /Y capacitor-student.config.ts capacitor.config.ts >nul 2>&1

echo [1/7] Patching version %VERSION% (code %VERSION_CODE%)...
node tools/patch-version.mjs %VERSION% %VERSION_CODE%
if errorlevel 1 ( echo ERROR: version patch failed & pause & exit /b 1 )

echo [2/7] Preparing web assets...
node tools/prepare-student.mjs
if errorlevel 1 ( echo ERROR: prepare failed & pause & exit /b 1 )

echo [3/7] Verifying config = STUDENT...
node -e "const fs=require('fs');const t=fs.readFileSync('capacitor.config.ts','utf8');if(!t.includes('com.nkseduorbit.student')){process.stderr.write('ERROR: capacitor.config.ts student config नाही!\n');process.exit(1);}console.log('  OK — com.nkseduorbit.student');"
if errorlevel 1 ( echo ERROR: config verify failed & pause & exit /b 1 )

echo [4/7] Patching applicationId → com.nkseduorbit.student ...
node tools/patch-appid.mjs com.nkseduorbit.student
if errorlevel 1 ( echo ERROR: applicationId patch failed & pause & exit /b 1 )

echo [5/7] Setting Nks EduOrbit icon + app name...
copy /Y icons-student\ic_launcher_background.xml android\app\src\main\res\values\ic_launcher_background.xml >nul 2>&1
copy /Y icons-student\strings.xml android\app\src\main\res\values\strings.xml >nul 2>&1

:: MainActivity.java lives in android/, which is gitignored (build artifact,
:: regenerated by `npx cap add android`) — android-student/MainActivity.java
:: is the tracked source of truth (adds real HTML5-Fullscreen support for
:: the embedded YouTube player; see its own comments), copied in here same
:: as the icon/strings overrides just above.
if not exist android\app\src\main\java\com\nkseduorbit\student\ mkdir android\app\src\main\java\com\nkseduorbit\student\ >nul 2>&1
copy /Y android-student\MainActivity.java android\app\src\main\java\com\nkseduorbit\student\MainActivity.java >nul 2>&1

echo [6/7] Capacitor sync...
call npx cap sync android
if errorlevel 1 (
  echo ERROR: cap sync failed
  pause & exit /b 1
)

echo [7/7] Building APK via Gradle (clean + assembleRelease)...
pushd android
:: Android Studio auto-generates gradle-daemon-jvm.properties pinning vendor=jetbrains,
:: which breaks CLI builds (no JBR on PATH). Remove it so Gradle uses JAVA_HOME (Temurin 21).
if exist gradle\gradle-daemon-jvm.properties del gradle\gradle-daemon-jvm.properties >nul 2>&1
call gradlew.bat clean
if errorlevel 1 ( popd & echo ERROR: Gradle clean failed & copy /Y ..\capacitor-student.config.ts ..\capacitor.config.ts >nul 2>&1 & pause & exit /b 1 )
call gradlew.bat assembleRelease
set BUILD_ERR=%errorlevel%
popd
if %BUILD_ERR% neq 0 (
  echo ERROR: Gradle build failed — खालील errors बघा
  copy /Y capacitor-student.config.ts capacitor.config.ts >nul 2>&1
  pause & exit /b 1
)

:: APK rename + move to release folder
if not exist android\app\release\ mkdir android\app\release\
if not exist "android\app\build\outputs\apk\release\app-release.apk" (
  echo ERROR: built APK not found ^(android\app\build\outputs\apk\release\app-release.apk^) — Gradle output missing
  copy /Y capacitor-student.config.ts capacitor.config.ts >nul 2>&1
  pause & exit /b 1
)
copy /Y "android\app\build\outputs\apk\release\app-release.apk" "android\app\release\Student%VERSION%.apk" >nul
if not exist "android\app\release\Student%VERSION%.apk" (
  echo ERROR: APK copy/rename failed
  copy /Y capacitor-student.config.ts capacitor.config.ts >nul 2>&1
  pause & exit /b 1
)

:: Restore student config (safe default)
copy /Y capacitor-student.config.ts capacitor.config.ts >nul 2>&1

:: Verify — applicationId confirm करा
echo.
echo  Verifying APK applicationId...
"C:\Users\A\AppData\Local\Android\Sdk\build-tools\37.0.0\aapt.exe" dump badging "android\app\release\Student%VERSION%.apk" 2>nul | findstr "^package:"

echo.
echo ========================================
echo  Student APK ready!
echo ========================================
echo  App ID   : com.nkseduorbit.student
echo  App Name : Nks EduOrbit
echo  Icon     : Navy (#001F5C)
echo  Version  : %VERSION% (code %VERSION_CODE%)
echo  APK      : android\app\release\Student%VERSION%.apk
echo.
pause
